### ISSUE TITLE
Hint for documentation

### ISSUE THREAD

**Issue by one7two99** [dmueckli/webexnotification#5]
Hello Dennis,
thank you for this plugin - it's great and seems not to get the recognition it needs.
I have some suggestions regarding tedocumentation:
Two important things which needs to be done prior using the script is to setup a WebEx Bot and get the WebEx Room ID.
Maybe adding the link, where this can be done will make it easier for new users:

WebEx Bots/Apps:
https://developer.webex.com/my-apps/
To create a new WebEx Chat Bot:
https://developer.webex.com/my-apps/new/bot

To find out the Room ID:
https://developer.webex.com/docs/api/v1/rooms/list-rooms

Keep up the great work 
One7two99

**Comment by dmueckli** [comment]
Hey One7two99,

thank you for your feedback and the suggestion! Much appreciated!

I have adopted the links right away and matched the readme. Glad I could help someone with the script or at least saved time.

Cheers!
Dennis
